version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tienganh123_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: tienganh123_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Sau này có thể thêm pgAdmin vào đây để quản lý DB bằng giao diện web nếu muốn

volumes:
  postgres_data:
